#!/bin/sh
# default-setting
#
uci set luci.main.lang=zh_cn
uci set luci.main.mediaurlbase='/luci-static/argon'
uci commit luci
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system

# 外网通过dhcp获取ip
uci set network.wan=interface
uci set network.wan.proto='dhcp'
uci set network.wan.type='bridge'
uci set network.wan.ifname='eth0'
# 默认内网 ip
uci set network.lan.ipaddr='192.168.1.254'
uci set network.lan.ifname='eth1'
uci commit network

uci set firewall.@zone[0].forward=ACCEPT
uci set firewall.@zone[0].network='wan'
uci set firewall.@zone[0].input=ACCEPT
uci set firewall.@zone[0].output=ACCEPT
uci set firewall.@zone[0].forward=ACCEPT
uci commit firewall

uci set fstab.@global[0].anon_mount=1
uci commit fstab

uci set dropbear.@dropbear[0].PasswordAuth='on'
uci set dropbear.@dropbear[0].Port='22'
uci set dropbear.@dropbear[0].Interface='wan'
uci set dropbear.@dropbear[0].GatewayPorts='on'
uci commit dropbear

uci set ttyd.@ttyd[0].command='/usr/libexec/login.sh'
uci commit ttyd

# rm -f /usr/lib/lua/luci/view/admin_status/index/mwan.htm
# rm -f /usr/lib/lua/luci/view/admin_status/index/upnp.htm
# rm -f /usr/lib/lua/luci/view/admin_status/index/ddns.htm
# rm -f /usr/lib/lua/luci/view/admin_status/index/minidlna.htm
# sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/aria2.lua
# sed -i 's/services/nas/g' /usr/lib/lua/luci/view/aria2/overview_status.htm
# sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/hd_idle.lua
# sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/samba.lua
# sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/samba4.lua
# sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/minidlna.lua
# sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/transmission.lua
# sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/mjpg-streamer.lua
# sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/p910nd.lua
# sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/usb_printer.lua
# sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/xunlei.lua
# sed -i 's/services/nas/g'  /usr/lib/lua/luci/view/minidlna_status.htm
sed -i 's/\"services\"/\"vpn\"/g' /usr/lib/lua/luci/controller/shadowsocksr.lua
sed -i 's/services/vpn/g' /usr/lib/lua/luci/model/cbi/shadowsocksr/*
sed -i 's/services/vpn/g' /usr/lib/lua/luci/view/shadowsocksr/*
sed -i 's/\"services\"/\"vpn\"/g' /usr/share/shadowsocksr/*
sed -i 's/\"services\"/\"vpn\"/g' /usr/lib/lua/luci/controller/frp.lua
sed -i 's/\"services\"/\"vpn\"/g' /usr/lib/lua/luci/model/cbi/frp/*
sed -i 's/services/vpn/g' /usr/lib/lua/luci/view/frp/*
sed -i 's/\"services\"/\"network\"/g' /usr/lib/lua/luci/controller/upnp.lua
sed -i 's/services/network/g' /usr/lib/lua/luci/view/upnp_status.htm
sed -i 's/\"services\"/\"vpn\"/g' /usr/lib/lua/luci/controller/ddnsto.lua
sed -i 's/services/vpn/g' /usr/lib/lua/luci/view/ddnsto*
sed -i 's/\"services\"/\"vpn\"/g' /usr/lib/lua/luci/controller/openvpn.lua
sed -i 's/\"services\"/\"vpn\"/g' /usr/lib/lua/luci/model/cbi/openvpn*
sed -i 's/services/vpn/g' /usr/lib/lua/luci/view/openvpn/*


ln -sf /sbin/ip /usr/bin/ip
sed -i 's#downloads.openwrt.org#mirrors.cloud.tencent.com/lede#g' /etc/opkg/distfeeds.conf
sed -i 's/root::0:0:99999:7:::/root:$1$a7$dQvBJz5LDDevjUZrjdbJj0:0:0:99999:7:::/g' /etc/shadow
sed -i "s/# //g" /etc/opkg/distfeeds.conf
sed -i '/openwrt_luci/ { s/snapshots/releases\/18.06.9/g; }'  /etc/opkg/distfeeds.conf
echo "15 */3 * * * /bin/bastip domain-1.com" >> /etc/crontabs/root
# for bastip test
mkdir -p /etc/ssrplus/
echo 'speed.cloudflare.com' > /etc/ssrplus/white.list
echo 'service.udpfile.com' >> /etc/ssrplus/white.list

sed -i '/REDIRECT --to-ports 53/d' /etc/firewall.user
echo 'iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user
echo 'iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user
echo '[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user
echo '[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user

echo "log-facility=/dev/null" >> /etc/dnsmasq.conflib/wifi/mac80211.sh
echo 'hsts=0' > /root/.wgetrc
rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache
exit 0